### ISSUE TITLE
How to apply ni-control-id in some other methods

### ISSUE THREAD

**Issue by eddieduy** [ni/webvi-examples#111]
I see the control in LabVIEW NXG has the format ni-control-id='xx'. How can I apply it into some methods using the ID such as `document.getElementById("42").innerHTML = "test"` ?

**Comment by rajsite** [comment]
Hi @eddieduy the GitHub issues are a great place to report bugs in the examples but general questions will reach a bigger audience in the LabVIEW Discussion Forums: https://forums.ni.com/t5/LabVIEW/bd-p/170

If you are looking for an element that is designed to have the contents replaced, as in the provided example, you may instead want to use the HTML Placeholder Container as discussed in the topic [Creating UI Elements with JavaScript](https://www.ni.com/documentation/en/labview-web-module/latest/manual/create-ui-elements-with-javascript/).

Alternatively, if you do want to add an identifier to controls some approaches are:

1. Adding a class (recommended):

   In LabVIEW NXG when you select a control you can set a HTML class attribute in the properties pane. You can then use the CSS class selector syntax to find the element. 

   For example, If I add the class `my_custom_control` in the HTML class attribute property pane, then the CSS class selector would be `.my_custom_control` (**Note** that the selector is the class prefixed with a dot). You can than query the CSS selector from JavaScript using `document.querySelector('.my_custom_control')`. 

   The help topic [Best Practices for Customizing the Appearance of Controls in a WebVI](https://www.ni.com/documentation/en/labview-web-module/5.0/manual/best-practices-customizing-controls-in-webvi/) describes how to use the NXG editor to specify classes on a control.

2. Directly edit the HTML (advanced): 

   An alternative if you want to specify the `id` specifically on an element instead of a `class` is to use the Edit HTML Source button to directly edit the HTML of a WebVI and add an `id` to the desired element.

I'll go ahead and close out this issue but if you have additional questions feel free to ask in the LabVIEW Discussion Forums!
